# Generated by Django 3.2.15 on 2022-08-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbasho', '0002_auto_20220816_0352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stable',
            name='unique_name',
        ),
        migrations.RemoveConstraint(
            model_name='stable',
            name='unique_name_kanji',
        ),
        migrations.AddConstraint(
            model_name='stable',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_stable_name'),
        ),
        migrations.AddConstraint(
            model_name='stable',
            constraint=models.UniqueConstraint(fields=('name_kanji',), name='unique_stable_name_kanji'),
        ),
        migrations.AddConstraint(
            model_name='wrestler',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name'), name='unique_wrestler_name'),
        ),
        migrations.AddConstraint(
            model_name='wrestler',
            constraint=models.UniqueConstraint(fields=('last_name_kanji', 'first_name_kanji'), name='unique_wrestler_name_kanji'),
        ),
    ]
