# Generated by Django 3.2.15 on 2022-08-21 12:57

from django.db import migrations, models
import django.db.models.deletion
import hbasho.utils


class Migration(migrations.Migration):

    dependencies = [
        ('hbasho', '0003_auto_20220816_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(choices=[(1, 'TOKYO'), (2, 'OSAKA'), (3, 'NAGOYA'), (4, 'FUKUOKA')], default=hbasho.utils.TournamentLocations['TOKYO'])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hbasho.wrestler')),
            ],
        ),
    ]
