# Generated by Django 3.2.15 on 2022-09-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbasho', '0004_auto_20220907_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='birthplace',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='retirement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='stable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hbasho.stable'),
        ),
        migrations.DeleteModel(
            name='WrestlerProfile',
        ),
    ]
