# Generated by Django 3.2.15 on 2022-09-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hbasho', '0006_auto_20220907_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrestlerRecord',
            fields=[
                ('wrestler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hbasho.wrestler')),
                ('wins', models.IntegerField(default=0)),
                ('lossess', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('championships_makuuchi', models.IntegerField(default=0)),
                ('kinboshi', models.IntegerField(default=0)),
                ('shukun_prizes', models.IntegerField(default=0)),
                ('kanto_prizes', models.IntegerField(default=0)),
                ('gino_prizes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rank',
            name='unique_rank_title',
        ),
        migrations.RemoveConstraint(
            model_name='stable',
            name='unique_stable_name',
        ),
        migrations.RemoveConstraint(
            model_name='stable',
            name='unique_stable_name_kanji',
        ),
        migrations.RemoveField(
            model_name='match',
            name='division',
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='winner', to='hbasho.wrestler'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='stable',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='stable',
            name='name_kanji',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='champion', to='hbasho.wrestler'),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='birthplace',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='wrestler',
            name='stable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hbasho.stable'),
        ),
        migrations.AddField(
            model_name='wrestlerrecord',
            name='highest_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hbasho.rank'),
        ),
    ]
