# Generated by Django 3.2.15 on 2022-09-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbasho', '0007_auto_20220912_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='order_by',
        ),
    ]
